### ISSUE TITLE
Brainstorming things that could go in this repo

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/nslsii#1]
A partial list:

* Ophyd devices for IOCs that are custom to NSLS-II
* A template IPython profile startup directory that includes such NSLS-II-isms as pyOlog configuration
* Asset handlers for file layouts custom to NSLS-II
* Analysis code (perhaps ultimately on its way to scikit-beam, but that requires more community review/approval)

**Comment by danielballan** [comment]
If it doesn't go without saying, thanks for getting the ball rolling on this @stuwilkins!

**Comment by stuwilkins** [comment]
@danielballan that was my suggestion also, PR #2 is my suggestion on this plus the directory layout. The only question I have is how to include templates given that they are not intended to be run or imported as a package. Perhaps an `examples` or `templates` directory?

**Comment by danielballan** [comment]
Maybe we can include a [cookiecutter](https://cookiecutter.readthedocs.io/en/latest/readme.html) designed to create a new subpackage.

**Comment by danielballan** [comment]
Again see https://github.com/NSLS-II/docs/pull/77 for where we landed on this.
