### ISSUE TITLE
Make logging more forgiving about not being able to open /var/log/bluesky.log

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/nslsii#111]
Reported by @tacaswell from the trenches

**Comment by stuartcampbell** [comment]
If we can't write to `/var/log/bluesky.log` would be fall back to somewhere that is always writable like `/tmp/bluesky.log` and then if that (for some unknown reason) is not writeable descend to just `/dev/null` 😄

**Comment by jklynch** [comment]
I believe this was resolved by #89.
