### ISSUE TITLE
ENH: parametrize TwoButtonShutter

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/nslsii#26]
Currently, the `TwoButtonShutter` class has hard-coded string values for opening/closing the shutter (`open_str = 'Open'` and `close_str = 'Close'`):
https://github.com/NSLS-II/nslsii/blob/575b21c1d16dc4af4317c35c284e41e8cd9a35fb/nslsii/devices.py#L9-L25

SMI needs [`Insert`/`Retract`](https://github.com/NSLS-II-SMI/ipython_ophyd/blob/b358d1ed5d1d19addc279c9b15a05ead0aa65998/profile_collection/startup/08-shutter.py#L17-L18) combinations.

Some other beamlines may have the same. Maybe SMI can use the same approach as [PDF](https://github.com/NSLS-II-PDF/profile_collection/blob/ce6bdc75e5002d4c278b2ff8ad12473505f3a3f8/startup/12-motors.py#L53-L57) and standardize `Open`/`Close` user-facing commands.

**Comment by tacaswell** [comment]
The idea was to paramterize this by sub-classing the it as

```python
class SMITwoButtonShutter(TwoButtonShutter):
    open_val = 'Inserted'
    close_val = 'Retracted'
```

As this is a property of the server so it should be a class level attribute (at least that was the thinking).

**Comment by mrakitin** [comment]
Thanks @tacaswell! That seems to be a good solution. Just one question - should it be `open_val`/`close_val`, or `open_str`/`close_str`?

**Comment by tacaswell** [comment]
Check the code, but iirc `*_val` is the enum string we are watching to make sure it did the thing we told it to and `*_str` is the input that we accept through `set`.

**Comment by mrakitin** [comment]
Yes, that's exactly what's implemented in the code. SMI's case uses [different inputs](https://github.com/NSLS-II-SMI/ipython_ophyd/blob/b358d1ed5d1d19addc279c9b15a05ead0aa65998/profile_collection/startup/08-shutter.py#L16-L18) for `set`:
```py
    # user facing commands
    open_str = 'Insert'
    close_str = 'Retract'
```
The rest seems identical. I'll update it at SMI next week.

**Comment by awalter-bnl** [comment]
This will also be resolved with the new version, called `EPS_Two_State_device` in nslsii. the PR is [here](https://github.com/NSLS-II/nslsii/pull/52)
