### ISSUE TITLE
Repo name is nsls-ii-tools and package name is nsls2tools?

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/nslsii#3]
I didn't catch this inconsistency when reviewing #2. Our choices are:

* leave as is
* change repo name to nsls2tools, which is inconsistent with the name printed on our building
* change package name to nsls_ii_tools or nslsii_tools

**Comment by danielballan** [comment]
We could also just call the package nslsii or nsls_ii and drop the 'tools'. I kind of like that.

**Comment by stuartcampbell** [comment]
I've been thinking, why not just call the repo `nsls2tools` as well ?  Then we are consistent ?

**Comment by tacaswell** [comment]
This is a package to convert nsls into tools? ;)

I like naming the package `nslsii`

**Comment by danielballan** [comment]
I also like `nslsii`. When this was raised in the past, someone (don't recall who) raised the concern that it squats too broad on a scope. In my opinion, a Python library that provides data acquisition and analysis tools for all NSLS-II beamlines is sufficiently broad to claim `nslsii` on PyPI.

**Comment by danielballan** [comment]
Done.
