### ISSUE TITLE
provide a reasonable bluesky log file path for Windows

### ISSUE THREAD

**Issue by jklynch** [NSLS-II/nslsii#84]
The bluesky log path is /var/log/bluesky/bluesky.log. This is not reasonable for Windows.

**Comment by danielballan** [comment]
The widely-used solution for this is https://pypi.org/project/appdirs/

For the sake of prioritization, do we have any Windows bluesky deployments left now that SST moved to Linux? I think there might be one, but I can't immediately think of it.

**Comment by tacaswell** [comment]
This library is endorsed by at least one windows based core cpython dev.
